language: python

python:
  - 2.6
  - 2.7

env:

install:
  - pip install -r requirements.txt

script:
  - nosetests --with-cover --cover-package pandas_highcharts pandas_highcharts

after_success: coveralls
